version: '3.8'

services:
  # Default service - Utah Hockey Club
  nhl-dashboard:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TEAM_CODE=UTA
      # Optional: Enable Slack notifications for Utah Mammoth Team Store alerts
      # - SLACK_WEBHOOK_URL=https://example.com/your-slack-webhook-url
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Example: Run multiple team dashboards on different ports
  # Uncomment and modify as needed
  
  # nhl-dashboard-avalanche:
  #   build: .
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - TEAM_CODE=COL
  #   restart: unless-stopped
  
  # nhl-dashboard-knights:
  #   build: .
  #   ports:
  #     - "8082:8080"
  #   environment:
  #     - TEAM_CODE=VGK
  #   restart: unless-stopped

networks:
  default:
    name: nhl-dashboard-network
