---
# Test 1: Minimal Alpine with same security context
apiVersion: v1
kind: Pod
metadata:
  name: test-alpine-security
  namespace: hockey-dashboard
  labels:
    test: diagnostic
spec:
  restartPolicy: Never
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
  containers:
  - name: test
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "=== Test 1: Basic shell execution ==="
        echo "Running as user: $(id)"
        echo "Architecture: $(uname -m)"
        echo "Kernel: $(uname -r)"
        echo ""
        echo "=== Test 2: Execute a simple binary ==="
        /bin/busybox echo "Busybox works!"
        echo ""
        echo "=== Test 3: Create and execute custom binary ==="
        cat > /tmp/hello.sh <<'EOFTEST'
        #!/bin/sh
        echo "Custom script works!"
        EOFTEST
        chmod +x /tmp/hello.sh
        /tmp/hello.sh
        echo ""
        echo "=== Test 4: Check available shells ==="
        ls -la /bin/sh /bin/busybox
        echo ""
        echo "=== All tests passed! ==="
        sleep 30
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault

---
# Test 2: Our actual image with debug output
apiVersion: v1
kind: Pod
metadata:
  name: test-hockey-debug
  namespace: hockey-dashboard
  labels:
    test: diagnostic
spec:
  restartPolicy: Never
  securityContext:
    fsGroup: 1001
    runAsNonRoot: false
  containers:
  - name: test
    image: jshillingburg/hockey_home_dashboard:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "=== Diagnostic Test for Hockey Dashboard ==="
        echo "Running as user: $(id)"
        echo "Architecture: $(uname -m)"
        echo "Kernel: $(uname -r)"
        echo ""
        echo "=== Checking web_server binary ==="
        ls -la /app/web_server
        file /app/web_server 2>&1 || echo "file command not available"
        echo ""
        echo "=== Trying to execute web_server ==="
        /app/web_server --help 2>&1 || echo "Execution failed with: $?"
        echo ""
        echo "=== Checking /bin/sh ==="
        ls -la /bin/sh
        echo ""
        sleep 30
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    env:
    - name: TEAM_CODE
      value: "UTA"

---
# Test 3: Our image without security restrictions
apiVersion: v1
kind: Pod
metadata:
  name: test-hockey-permissive
  namespace: hockey-dashboard
  labels:
    test: diagnostic
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: jshillingburg/hockey_home_dashboard:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "=== Test with relaxed security ==="
        echo "Running as user: $(id)"
        echo ""
        echo "=== Trying to execute web_server ==="
        /app/web_server --help 2>&1 || echo "Execution failed with: $?"
        echo ""
        sleep 30
    env:
    - name: TEAM_CODE
      value: "UTA"

---
# Test 4: Simple Go binary test
apiVersion: v1
kind: Pod
metadata:
  name: test-go-binary
  namespace: hockey-dashboard
  labels:
    test: diagnostic
spec:
  restartPolicy: Never
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
  containers:
  - name: test
    image: golang:1.23-alpine
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "=== Building and testing a minimal Go binary ==="
        cd /tmp
        cat > hello.go <<'EOFGO'
        package main
        import "fmt"
        func main() {
            fmt.Println("Hello from Go!")
        }
        EOFGO
        echo "Building static ARM64 binary..."
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-w -s" -o hello hello.go
        echo "Binary created:"
        ls -la hello
        file hello 2>&1 || echo "file command not available"
        echo ""
        echo "Executing binary..."
        ./hello
        echo ""
        echo "=== Test completed successfully! ==="
        sleep 30
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault

