package models

// TeamConfig holds configuration for a specific NHL team
type TeamConfig struct {
	Code            string `json:"code"`            // NHL team code (e.g., "UTA", "COL", "NYR")
	Name            string `json:"name"`            // Display name (e.g., "Utah Hockey Club", "Colorado Avalanche")
	ShortName       string `json:"shortName"`       // Short name (e.g., "Utah", "Avalanche")
	City            string `json:"city"`            // City name (e.g., "Salt Lake City", "Denver")
	Arena           string `json:"arena"`           // Home arena (e.g., "Delta Center", "Ball Arena")
	PrimaryColor    string `json:"primaryColor"`    // Primary team color for UI
	SecondaryColor  string `json:"secondaryColor"`  // Secondary team color for UI
	BackgroundImage string `json:"backgroundImage"` // Background image path
	FaviconPath     string `json:"faviconPath"`     // Favicon image path
	LogoPath        string `json:"logoPath"`        // Logo image path
}

// GetDefaultTeamConfig returns the default team configuration (Utah Hockey Club)
func GetDefaultTeamConfig() TeamConfig {
	return TeamConfig{
		Code:            "UTA",
		Name:            "Utah Hockey Club",
		ShortName:       "Utah",
		City:            "Salt Lake City",
		Arena:           "Delta Center",
		PrimaryColor:    "#6CACE3",
		SecondaryColor:  "#000000",
		BackgroundImage: "/static/media/photos/mammoth/mammoth.png",
		FaviconPath:     "/static/media/photos/mammoth/mammoth-favicon.png",
		LogoPath:        "/static/media/photos/mammoth/mammoth-logo.png",
	}
}

// GetTeamConfigByCode returns team configuration for a given NHL team code
// If the code is not found, returns the default configuration
func GetTeamConfigByCode(code string) TeamConfig {
	teamConfigs := map[string]TeamConfig{
		"UTA": {
			Code:            "UTA",
			Name:            "Utah Hockey Club",
			ShortName:       "Mammoth",
			City:            "Salt Lake City",
			Arena:           "Delta Center",
			PrimaryColor:    "#6CACE3",
			SecondaryColor:  "#000000",
			BackgroundImage: "/static/media/photos/mammoth/mammoth.png",
			FaviconPath:     "/static/media/photos/mammoth/mammoth-favicon.png",
			LogoPath:        "/static/media/photos/mammoth/mammoth-logo.png",
		},
		"COL": {
			Code:            "COL",
			Name:            "Colorado Avalanche",
			ShortName:       "Avalanche",
			City:            "Denver",
			Arena:           "Ball Arena",
			PrimaryColor:    "#6f263d",
			SecondaryColor:  "#236192",
			BackgroundImage: "/static/media/photos/avalanche/colorado-avalanche-background.png",
			FaviconPath:     "/static/media/photos/avalanche/colorado-avalanche-logo.png",
			LogoPath:        "/static/media/photos/avalanche/colorado-avalanche-logo.png",
		},
		"VGK": {
			Code:            "VGK",
			Name:            "Vegas Golden Knights",
			ShortName:       "Golden Knights",
			City:            "Las Vegas",
			Arena:           "T-Mobile Arena",
			PrimaryColor:    "#b4975a",
			SecondaryColor:  "#333f42",
			BackgroundImage: "/static/media/photos/golden knights/vegas-golden-knights-background.png",
			FaviconPath:     "/static/media/photos/golden knights/vegas-golden-knights-logo.png",
			LogoPath:        "/static/media/photos/golden knights/vegas-golden-knights-logo.png",
		},
		"NYR": {
			Code:            "NYR",
			Name:            "New York Rangers",
			ShortName:       "Rangers",
			City:            "New York",
			Arena:           "Madison Square Garden",
			PrimaryColor:    "#0038a8",
			SecondaryColor:  "#ce1126",
			BackgroundImage: "/static/media/photos/rangers/new-york-rangers-background.jpeg",
			FaviconPath:     "/static/media/photos/rangers/new-york-rangers-logo.png",
			LogoPath:        "/static/media/photos/rangers/new-york-rangers-logo.png",
		},
		"BOS": {
			Code:            "BOS",
			Name:            "Boston Bruins",
			ShortName:       "Bruins",
			City:            "Boston",
			Arena:           "TD Garden",
			PrimaryColor:    "#ffb81c",
			SecondaryColor:  "#000000",
			BackgroundImage: "/static/media/photos/bruins/boston-bruins-background.png",
			FaviconPath:     "/static/media/photos/bruins/boston-bruins-logo.png",
			LogoPath:        "/static/media/photos/bruins/boston-bruins-logo.png",
		},
		"TOR": {
			Code:            "TOR",
			Name:            "Toronto Maple Leafs",
			ShortName:       "Maple Leafs",
			City:            "Toronto",
			Arena:           "Scotiabank Arena",
			PrimaryColor:    "#003e7e",
			SecondaryColor:  "#ffffff",
			BackgroundImage: "/static/media/photos/maple leafs/toronto-maple-leafs-background.png",
			FaviconPath:     "/static/media/photos/maple leafs/toronto-maple-leafs-logo.png",
			LogoPath:        "/static/media/photos/maple leafs/toronto-maple-leafs-logo.png",
		},
		"EDM": {
			Code:            "EDM",
			Name:            "Edmonton Oilers",
			ShortName:       "Oilers",
			City:            "Edmonton",
			Arena:           "Rogers Place",
			PrimaryColor:    "#041e42",
			SecondaryColor:  "#ff4c00",
			BackgroundImage: "/static/media/photos/oilers/edmonton-oilers-background.jpg",
			FaviconPath:     "/static/media/photos/oilers/edmonton-oilers-logo.png",
			LogoPath:        "/static/media/photos/oilers/edmonton-oilers-logo.png",
		},
		"FLA": {
			Code:            "FLA",
			Name:            "Florida Panthers",
			ShortName:       "Panthers",
			City:            "Sunrise",
			Arena:           "Amerant Bank Arena",
			PrimaryColor:    "#041e42",
			SecondaryColor:  "#c8102e",
			BackgroundImage: "/static/media/photos/panthers/florida-panthers-background.jpeg",
			FaviconPath:     "/static/media/photos/panthers/florida-panthers-logo.jpg",
			LogoPath:        "/static/media/photos/panthers/florida-panthers-logo.jpg",
		},
		"CAR": {
			Code:            "CAR",
			Name:            "Carolina Hurricanes",
			ShortName:       "Hurricanes",
			City:            "Raleigh",
			Arena:           "PNC Arena",
			PrimaryColor:    "#cc0000",
			SecondaryColor:  "#000000",
			BackgroundImage: "/static/media/photos/hurricanes/carolina-hurricanes-background.png",
			FaviconPath:     "/static/media/photos/hurricanes/carolina-hurricanes-logo.jpg",
			LogoPath:        "/static/media/photos/hurricanes/carolina-hurricanes-logo.jpg",
		},
		"BUF": {
			Code:            "BUF",
			Name:            "Buffalo Sabres",
			ShortName:       "Sabres",
			City:            "Buffalo",
			Arena:           "KeyBank Center",
			PrimaryColor:    "#003087",
			SecondaryColor:  "#fcb514",
			BackgroundImage: "/static/media/photos/sabers/buffalo-sabers-background.png",
			FaviconPath:     "/static/media/photos/sabers/buffalo-sabers-background.png",
			LogoPath:        "/static/media/photos/sabers/buffalo-sabers-background.png",
		},
		"CBJ": {
			Code:            "CBJ",
			Name:            "Columbus Blue Jackets",
			ShortName:       "Blue Jackets",
			City:            "Columbus",
			Arena:           "Nationwide Arena",
			PrimaryColor:    "#002654",
			SecondaryColor:  "#ce1126",
			BackgroundImage: "/static/media/photos/blue jackets/columbus-blue-jackets-background.jpg",
			FaviconPath:     "/static/media/photos/blue jackets/columbus-blue-jackets-logo.jpg",
			LogoPath:        "/static/media/photos/blue jackets/columbus-blue-jackets-logo.jpg",
		},
		"DET": {
			Code:            "DET",
			Name:            "Detroit Red Wings",
			ShortName:       "Red Wings",
			City:            "Detroit",
			Arena:           "Little Caesars Arena",
			PrimaryColor:    "#ce1126",
			SecondaryColor:  "#ffffff",
			BackgroundImage: "/static/media/photos/red wings/detroit-red-wings-background.png",
			FaviconPath:     "/static/media/photos/red wings/detroit-red-wings-logo.png",
			LogoPath:        "/static/media/photos/red wings/detroit-red-wings-logo.png",
		},
		"NYI": {
			Code:            "NYI",
			Name:            "New York Islanders",
			ShortName:       "Islanders",
			City:            "Elmont",
			Arena:           "UBS Arena",
			PrimaryColor:    "#00539b",
			SecondaryColor:  "#f47d30",
			BackgroundImage: "/static/media/photos/islanders/new-york-islanders-background.jpg",
			FaviconPath:     "/static/media/photos/islanders/new-york-islanders-logo.jpg",
			LogoPath:        "/static/media/photos/islanders/new-york-islanders-logo.jpg",
		},
		"NJD": {
			Code:            "NJD",
			Name:            "New Jersey Devils",
			ShortName:       "Devils",
			City:            "Newark",
			Arena:           "Prudential Center",
			PrimaryColor:    "#ce1126",
			SecondaryColor:  "#000000",
			BackgroundImage: "/static/media/photos/devils/new-jersey-devils-background.jpg",
			FaviconPath:     "/static/media/photos/devils/new-jersey-devils-logo.webp",
			LogoPath:        "/static/media/photos/devils/new-jersey-devils-logo.webp",
		},
		"PHI": {
			Code:            "PHI",
			Name:            "Philadelphia Flyers",
			ShortName:       "Flyers",
			City:            "Philadelphia",
			Arena:           "Wells Fargo Center",
			PrimaryColor:    "#f74902",
			SecondaryColor:  "#000000",
			BackgroundImage: "/static/media/photos/flyers/philadelphia-flyers-background.png",
			FaviconPath:     "/static/media/photos/flyers/philadelphia-flyers-logo.png",
			LogoPath:        "/static/media/photos/flyers/philadelphia-flyers-logo.png",
		},
		"OTT": {
			Code:            "OTT",
			Name:            "Ottawa Senators",
			ShortName:       "Senators",
			City:            "Ottawa",
			Arena:           "Canadian Tire Centre",
			PrimaryColor:    "#c52032",
			SecondaryColor:  "#000000",
			BackgroundImage: "/static/media/photos/senators/ottawa-senators-background.jpeg",
			FaviconPath:     "/static/media/photos/senators/ottawa-senators-logo.png",
			LogoPath:        "/static/media/photos/senators/ottawa-senators-logo.png",
		},
		"MTL": {
			Code:            "MTL",
			Name:            "Montreal Canadiens",
			ShortName:       "Canadiens",
			City:            "Montreal",
			Arena:           "Bell Centre",
			PrimaryColor:    "#af1e2d",
			SecondaryColor:  "#192168",
			BackgroundImage: "/static/media/photos/canadiens/montreal-canadiens-background.jpeg",
			FaviconPath:     "/static/media/photos/canadiens/montreal-canadiens-logo.png",
			LogoPath:        "/static/media/photos/canadiens/montreal-canadiens-logo.png",
		},
		"WSH": {
			Code:            "WSH",
			Name:            "Washington Capitals",
			ShortName:       "Capitals",
			City:            "Washington",
			Arena:           "Capital One Arena",
			PrimaryColor:    "#041e42",
			SecondaryColor:  "#c8102e",
			BackgroundImage: "/static/media/photos/capitals/washington-capitals-background.jpeg",
			FaviconPath:     "/static/media/photos/capitals/washington-capitals-logo.png",
			LogoPath:        "/static/media/photos/capitals/washington-capitals-logo.png",
		},
		"TBL": {
			Code:            "TBL",
			Name:            "Tampa Bay Lightning",
			ShortName:       "Lightning",
			City:            "Tampa",
			Arena:           "Amalie Arena",
			PrimaryColor:    "#002868",
			SecondaryColor:  "#ffffff",
			BackgroundImage: "/static/media/photos/lightning/tampa-bay-lightning-background.jpeg",
			FaviconPath:     "/static/media/photos/lightning/tampa-bay-lightning-logo.png",
			LogoPath:        "/static/media/photos/lightning/tampa-bay-lightning-logo.png",
		},
		"PIT": {
			Code:            "PIT",
			Name:            "Pittsburgh Penguins",
			ShortName:       "Penguins",
			City:            "Pittsburgh",
			Arena:           "PPG Paints Arena",
			PrimaryColor:    "#000000",
			SecondaryColor:  "#fcb514",
			BackgroundImage: "/static/media/photos/penguins/pittsburgh-penguins-background.png",
			FaviconPath:     "/static/media/photos/penguins/pittsburgh-penguins-logo.png",
			LogoPath:        "/static/media/photos/penguins/pittsburgh-penguins-logo.png",
		},
		"CHI": {
			Code:            "CHI",
			Name:            "Chicago Blackhawks",
			ShortName:       "Blackhawks",
			City:            "Chicago",
			Arena:           "United Center",
			PrimaryColor:    "#cf0a2c",
			SecondaryColor:  "#000000",
			BackgroundImage: "/static/media/photos/blackhawks/chicago-blackhawks-background.png",
			FaviconPath:     "/static/media/photos/blackhawks/chicago-blackhawks-logo.png",
			LogoPath:        "/static/media/photos/blackhawks/chicago-blackhawks-logo.png",
		},
		"ANA": {
			Code:            "ANA",
			Name:            "Anaheim Ducks",
			ShortName:       "Ducks",
			City:            "Anaheim",
			Arena:           "Honda Center",
			PrimaryColor:    "#f47a38",
			SecondaryColor:  "#000000",
			BackgroundImage: "/static/media/photos/ducks/anaheim-ducks-background.png",
			FaviconPath:     "/static/media/photos/ducks/anaheim-ducks-logo.png",
			LogoPath:        "/static/media/photos/ducks/anaheim-ducks-logo.png",
		},
		"CGY": {
			Code:            "CGY",
			Name:            "Calgary Flames",
			ShortName:       "Flames",
			City:            "Calgary",
			Arena:           "Scotiabank Saddledome",
			PrimaryColor:    "#c8102e",
			SecondaryColor:  "#f1be48",
			BackgroundImage: "/static/media/photos/flames/calgary-flames-background.png",
			FaviconPath:     "/static/media/photos/flames/calgary-flames-logo.png",
			LogoPath:        "/static/media/photos/flames/calgary-flames-logo.png",
		},
		"MIN": {
			Code:            "MIN",
			Name:            "Minnesota Wild",
			ShortName:       "Wild",
			City:            "Saint Paul",
			Arena:           "Xcel Energy Center",
			PrimaryColor:    "#154734",
			SecondaryColor:  "#a6192e",
			BackgroundImage: "/static/media/photos/wild/minnesota-wild-background.jpeg",
			FaviconPath:     "/static/media/photos/wild/minnesota-wild-logo.png",
			LogoPath:        "/static/media/photos/wild/minnesota-wild-logo.png",
		},
		"DAL": {
			Code:            "DAL",
			Name:            "Dallas Stars",
			ShortName:       "Stars",
			City:            "Dallas",
			Arena:           "American Airlines Center",
			PrimaryColor:    "#006847",
			SecondaryColor:  "#8f8f8c",
			BackgroundImage: "/static/media/photos/stars/dallas-stars-background.jpeg",
			FaviconPath:     "/static/media/photos/stars/dallas-stars-logo.png",
			LogoPath:        "/static/media/photos/stars/dallas-stars-logo.png",
		},
		"LAK": {
			Code:            "LAK",
			Name:            "Los Angeles Kings",
			ShortName:       "Kings",
			City:            "Los Angeles",
			Arena:           "Crypto.com Arena",
			PrimaryColor:    "#111111",
			SecondaryColor:  "#a2aaad",
			BackgroundImage: "/static/media/photos/kings/los-angeles-kings-background.jpeg",
			FaviconPath:     "/static/media/photos/kings/los-angeles-kings-logo.png",
			LogoPath:        "/static/media/photos/kings/los-angeles-kings-logo.png",
		},
		"SJS": {
			Code:            "SJS",
			Name:            "San Jose Sharks",
			ShortName:       "Sharks",
			City:            "San Jose",
			Arena:           "SAP Center",
			PrimaryColor:    "#006d75",
			SecondaryColor:  "#ea7200",
			BackgroundImage: "/static/media/photos/sharks/san-jose-sharks-background.png",
			FaviconPath:     "/static/media/photos/sharks/san-jose-sharks-logo.png",
			LogoPath:        "/static/media/photos/sharks/san-jose-sharks-logo.png",
		},
		"NSH": {
			Code:            "NSH",
			Name:            "Nashville Predators",
			ShortName:       "Predators",
			City:            "Nashville",
			Arena:           "Bridgestone Arena",
			PrimaryColor:    "#ffb81c",
			SecondaryColor:  "#041e42",
			BackgroundImage: "/static/media/photos/predators/nashville-predators-background.png",
			FaviconPath:     "/static/media/photos/predators/nashville-predators-logo.png",
			LogoPath:        "/static/media/photos/predators/nashville-predators-logo.png",
		},
		"STL": {
			Code:            "STL",
			Name:            "St. Louis Blues",
			ShortName:       "Blues",
			City:            "St. Louis",
			Arena:           "Enterprise Center",
			PrimaryColor:    "#002f87",
			SecondaryColor:  "#fcb514",
			BackgroundImage: "/static/media/photos/blues/st-louis-blues-background.jpeg",
			FaviconPath:     "/static/media/photos/blues/st-louis-blues-logo.png",
			LogoPath:        "/static/media/photos/blues/st-louis-blues-logo.png",
		},
		"SEA": {
			Code:            "SEA",
			Name:            "Seattle Kraken",
			ShortName:       "Kraken",
			City:            "Seattle",
			Arena:           "Climate Pledge Arena",
			PrimaryColor:    "#001628",
			SecondaryColor:  "#99d9d9",
			BackgroundImage: "/static/media/photos/kraken/seattle-kraken-background.jpeg",
			FaviconPath:     "/static/media/photos/kraken/seattle-kraken-logo.png",
			LogoPath:        "/static/media/photos/kraken/seattle-kraken-logo.png",
		},
		"VAN": {
			Code:            "VAN",
			Name:            "Vancouver Canucks",
			ShortName:       "Canucks",
			City:            "Vancouver",
			Arena:           "Rogers Arena",
			PrimaryColor:    "#001f5b",
			SecondaryColor:  "#00843d",
			BackgroundImage: "/static/media/photos/canucks/vancouver-canucks-background.png",
			FaviconPath:     "/static/media/photos/canucks/vancouver-canucks-logo.png",
			LogoPath:        "/static/media/photos/canucks/vancouver-canucks-logo.png",
		},
		"WPG": {
			Code:            "WPG",
			Name:            "Winnipeg Jets",
			ShortName:       "Jets",
			City:            "Winnipeg",
			Arena:           "Bell MTS Place",
			PrimaryColor:    "#041e42",
			SecondaryColor:  "#004c97",
			BackgroundImage: "/static/media/photos/jets/winnipeg-jets-background.png",
			FaviconPath:     "/static/media/photos/jets/winnipeg-jets-logo.png",
			LogoPath:        "/static/media/photos/jets/winnipeg-jets-logo.png",
		},
		// Add more teams as needed - this covers popular teams for testing
	}

	if config, exists := teamConfigs[code]; exists {
		return config
	}

	// Return default if team code not found
	return GetDefaultTeamConfig()
}

// IsValidTeamCode checks if a team code is supported
func IsValidTeamCode(code string) bool {
	validCodes := []string{
		"UTA", "COL", "VGK", "NYR", "BOS", "TOR", "EDM", "FLA", "CAR", "BUF", "CBJ", "DET", "NYI", "NJD", "PHI", "OTT", "MTL", "WSH", "TBL", "PIT", "CHI", "ANA", "CGY", "MIN", "DAL", "LAK", "SJS", "NSH", "STL", "SEA", "VAN", "WPG",
		// Add more as needed
	}

	for _, validCode := range validCodes {
		if code == validCode {
			return true
		}
	}
	return false
}
